unique_ids:
  assets:
    standard-page.html: TAFMBOPVKFX7J3AHLYZJ3EX4FAIIVDOC
    theme.css: TQE32FTW4HB4NZJ3AVBVOFLIEF36EPKN
  forms:
    Form1: UZRSGI3ODGVCPHJ7CO424F7LVL5OFKGC
  modules: {}
  scripts: {}
  server_modules: {}
